### ISSUE TITLE
NewsLetter sending Tool

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Technical#140]
- Review the code in Newsletter sending tool 
- Review the emails of users who were not verified, find a way to skip sending to them or validate them quickly using email-validator. 
- Btw, what is the translation of email status = 0, 1, 2, 3? Would like to understand the logic so as to calculate how many users do we have and probability to reach to their emails. 
- need to send a newlsetter right after

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan Eman will send the information about the tool

**Comment by EmanHylooz** [comment]
0 = normal
1 = softbounce
2 = hardbounce 
3= complain (spam)

**Comment by EmanHylooz** [comment]
mark all auto-generated emails = 4

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz We can also use the same idea for not validated emails. mark all emails within  '2017-04-04' and '2017-07-25' as NotValidated emails = 5.
So by this we will not change anything in Tool and you will run from old tool :)

**Comment by Shimaa-Hassan** [comment]
And by this we will not add fake email status as it is notValidated f3lan :)

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan great idea ! Yes let us do that then :) 
As for the tool, I will send you the tool by email (as you told me you needed to change something in the code msh haik?) So instead of telling u about the virtual machine, i will just email it to you as a zipped folder and you take a look :)

**Comment by Shimaa-Hassan** [comment]
Ok I will see it from version u have to make sure all is Ok and didn't need change

**Comment by EmanHylooz** [comment]
Great, I shared it with you via DropBox. You should receive an email.

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz what is the last date u used tool ? as it is dll's and I cannot view code

**Comment by EmanHylooz** [comment]
I only use the .exe file... long long time ago. We didnt send newsletter
since over 2 years :(

**Comment by Shimaa-Hassan** [comment]
Ok are u sure this version u had skipped users with email status != 0

**Comment by Shimaa-Hassan** [comment]
As I cannot see code because it is dll's

**Comment by EmanHylooz** [comment]
No am not sure at all. Tamim gave it to me before he left.

**Comment by Shimaa-Hassan** [comment]
Ok so tamim not change code after give it to u. So I think version is OK but really i'm not sure. for save we just output new exe but not today

**Comment by EmanHylooz** [comment]
Sure. And the new .exe will have the amazon 52,000 users out too right?

**Comment by Shimaa-Hassan** [comment]
Now 52000 users is marked in database as email status = 5 So if tamim in this version u had skipped any emailstatus and just send to email status = 0 so all is OK

**Comment by EmanHylooz** [comment]
Okay good. So you advice to wait till you get us a new .exe so as to make
sure that all users with email != 0 will not be sent right?

**Comment by Shimaa-Hassan** [comment]
As I found in github tamim last change code of newslatter in 2016-08-30 and exe date is 2016-08-31 So by logic it is save to use tamim exe :)

**Comment by EmanHylooz** [comment]
Perfect :D

**Comment by EmanHylooz** [comment]
Sadly, the newsletter sender did not work, it threw an exception. 

Here is the log file of the exception: 
[Header] [Footer] [Header] 2017-08-19 09:05:06,607 [3] ERROR AbjjadLog [(null)] <(null)> - System.TypeInitializationException: The type initializer for 'Abjjad.Data.SessionHelper' threw an exception. ---> System.Data.SqlClient.SqlException: Login failed for user 'abjjaddbadmin'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at NHibernate.Connection.DriverConnectionProvider.GetConnection()
   at NHibernate.Tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.Prepare()
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.GetReservedWords(Dialect dialect, IConnectionHelper connectionHelper)
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.Update(ISessionFactory sessionFactory)
   at NHibernate.Impl.SessionFactoryImpl..ctor(Configuration cfg, IMapping mapping, Settings settings, EventListeners listeners)
   at NHibernate.Cfg.Configuration.BuildSessionFactory()
   at Abjjad.Data.SessionHelper..cctor() in C:\Work\Code\abjjad\Abjjad.Data\SessionHelper.cs:line 25
   --- End of inner exception stack trace ---
   at Abjjad.Data.SessionHelper.GetNewSession()
   at Abjjad.Repository.Queries.Members.MailableMemberCount.Execute() in C:\Work\Code\abjjad\Abjjad.Respository\Queries\Members\MailableMemberCount.cs:line 16
   at Abjjad.Service.MemberService.GetMailableMemberCount() in C:\Work\Code\abjjad\Abjjad.Service\MemberService.cs:line 1426
   at NewsletterSender.frmMain.Worker_DoWork(Object sender, DoWorkEventArgs e) in C:\Work\Code\abjjad\NewsletterSender\frmMain.cs:line 109
[Footer]

**Comment by EmanHylooz** [comment]
Here is what Tamim told me about the newsletter sender before he left: 

For the newsletter sender, do the following:
Go to AbjjadStudio server.
Go to C:\Abjjad\Tools\NewsletterSender
Delete Log folder
Find NewsletterSender.exe and start it
Fill the fields as follows:
Newsletter File: pick the HTML file for newsletter.
From (Email): the email to show in receivers' inboxes, (has to be @abjjad.com email).
From (Name): the name to show in receivers' inboxes
Subject.
Batch Number: Amazon limit us to 100,000 email per 24 hrs, so we need to send the newsletter in batches, we currently have around 165,000 valid emails so we need to send the email in 2 batches, type the number "1" first time you run this, after 24 hours you can run the tool again but type in number "2".
Click send.
You can see in the status bar what's going on.
the files in the Log folder should show you a list of emails who were sent the newsletter so far.

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz I will send u new exe "Login failed for user 'abjjaddbadmin'" because this is not user of production ?

**Comment by EmanHylooz** [comment]
​Wallahi ya shimaa I don't know what is the login, as it did not ask me to
login in the first place. ​

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Shimaa-Hassan** [comment]
I detect the problem and I will solve it and send u new exe

**Comment by EmanHylooz** [comment]
Thanks a lot :)

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Shimaa-Hassan** [comment]
I shared with u folder in Dropbox.

**Comment by EmanHylooz** [comment]
Hi Shimaa, 
I did not receive an email for dropbox, can you send me a link instead?

**Comment by EmanHylooz** [comment]
Found it, no  worries.
